### ISSUE TITLE
"cloning builder process: Operation not permitted"

### ISSUE THREAD

**Issue by edude03** [alexandergall/nixos-pxe-installer#3] opened 2018-12-03 10:54 UTC
I think I'm pretty close to getting this work, though it fails close to the end of build with the following error (sorry for the screen shot) 

![Imgur](https://i.imgur.com/RCBRlbQ.jpg)

This is installing Nixos 18.09, the closest issue I could find is [this](https://github.com/NixOS/nix/issues/1625), but I'm not sure how to proceed with debugging this

**Comment by alexandergall** [comment] 2019-01-08 14:12
This is caused by the new default `nix.useSandbox = true`. The installer executes `nix-env` in a chroot (via `nixos-enter`), which will enter another chroot when the sandbox is enabled. However, `clone(2)` specifically prohibits nested chroots, hence the error. This is fixed in 6bf285363033d38245b6a2d774d9e08f100b806e by disabling the sandbox for that particular invocation of `nix-env`. This appears to be a fundamental limitation but the workaround seems acceptable.

**Closed as completed by alexandergall** 2019-01-08 14:12 UTC
